project_id = "xlhkgiodihlchvoraplq"

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.external-create-user]
verify_jwt = false

[functions.external-delete-user]
verify_jwt = false

[functions.external-update-user]
verify_jwt = false
